import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {ReportStore} from '../src/index.mjs';
async function setup(t){const root=await mkdtemp(join(tmpdir(),'human-items-'));t.after(()=>rm(root,{recursive:true,force:true}));const core=new ReportStore({rootDir:root});let d=await core.createDraft({sessionId:'s',title:'fixture',markdown:'# Report\n\nGenerated unchanged\n\nOriginal'});d=await core.saveDraft({sessionId:'s',reportId:d.reportId,saveToken:d.saveToken,markdown:'# Report\n\nGenerated unchanged\n\nHuman correction',source:'user_prompt',instruction:'PRIVATE PROMPT'});return{root,core,d,b:{sessionId:'s',reportId:d.reportId}};}
const review=a=>({annotationId:a.annotationId,category:'correction',selected:true,visibility:'public',publicSource:'Public reference',localNote:'PRIVATE NOTE'});
const author={authorId:'fixture-user',displayName:'Fixture'};
test('human item references only human annotations, bounded schema and same-session token writes',async t=>{const{core,d,b}=await setup(t);const view=await core.getHumanItems(b);assert.equal(view.items.length,1);assert.equal(view.items[0].content,'Human correction');assert.ok(!view.items.some(i=>i.content?.includes('Generated')));const item=review(view.items[0]);await assert.rejects(core.getHumanItems({...b,sessionId:'other'}),{code:'NOT_FOUND'});await assert.rejects(core.saveHumanItems({...b,sessionId:'other',saveToken:d.saveToken,items:[item]}),{code:'NOT_FOUND'});for(const bad of [{...item,content:'fake'},{...item,before:'fake'},{...item,annotationId:'deleted-id'},{...item,category:'fake'},{...item,selected:'yes'},{...item,visibility:'secret'},{...item,id:'forged'}])await assert.rejects(core.saveHumanItems({...b,saveToken:d.saveToken,items:[bad]}),{code:'INVALID_INPUT'});const results=await Promise.allSettled([core.saveHumanItems({...b,saveToken:d.saveToken,items:[item]}),core.saveHumanItems({...b,saveToken:d.saveToken,items:[]})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.find(r=>r.status==='rejected').reason.code,'CONFLICT');assert.equal((await core.listVersions(b)).length,0);});
test('review choices restart, confirmed freeze and export only verified selected public nonstyle content',async t=>{const{core,root,d,b}=await setup(t);let v=await core.getHumanItems(b);v=await core.saveHumanItems({...b,saveToken:d.saveToken,items:[review(v.items[0])]});const reopened=new ReportStore({rootDir:root});assert.deepEqual(await reopened.getHumanItems(b),v);const noNote=review(v.items[0]);delete noNote.localNote;v=await reopened.saveHumanItems({...b,saveToken:v.saveToken,items:[noNote]});assert.equal(v.items[0].localNote,'PRIVATE NOTE');const confirmed=await reopened.confirm({...b,saveToken:v.saveToken,author});assert.equal(confirmed.humanItems[0].localNote,'PRIVATE NOTE');const current=await reopened.getDraft(b);await assert.rejects(reopened.saveHumanItems({...b,saveToken:current.saveToken,items:[]}),{code:'REVISION_REQUIRED'});const pub=await reopened.exportVersion({...b,versionId:'V1'});assert.equal(pub.humanItems.length,1);assert.equal(pub.humanItems[0].content,'Human correction');assert.equal(pub.humanItems[0].authorId,author.authorId);assert.ok(!JSON.stringify(pub).includes('PRIVATE'));assert.ok(!JSON.stringify(pub).includes('Original'));});
test('selection-only confirm returns original immutable version and revisions retain stable IDs',async t=>{const{core,d,b}=await setup(t);let view=await core.getHumanItems(b);view=await core.saveHumanItems({...b,saveToken:d.saveToken,items:[review(view.items[0])]});const first=await core.confirm({...b,saveToken:view.saveToken,author});let next=await core.startRevision({...b,versionId:'V1'});view=await core.getHumanItems(b);assert.equal(view.items[0].id,first.humanItems[0].id);view=await core.saveHumanItems({...b,saveToken:next.saveToken,items:[{...review(view.items[0]),selected:false}]});const same=await core.confirm({...b,saveToken:view.saveToken,author:{authorId:'other',displayName:'Other'}});assert.deepEqual(same,first);assert.equal((await core.getHumanItems(b)).items[0].selected,true);assert.equal((await core.listVersions(b)).length,1);next=await core.startRevision({...b,versionId:'V1'});next=await core.saveDraft({...b,saveToken:next.saveToken,source:'user_direct',markdown:next.markdown+'\n\nNew human addition'});const second=await core.confirm({...b,saveToken:next.saveToken,author});assert.equal(second.humanItems[0].id,first.humanItems[0].id);assert.equal((await core.exportVersion({...b,versionId:'V2'})).humanItems[0].content,'Human correction');});
test('local, style and unselected remain private; missing/deleted annotation cannot become retraction fact',async t=>{const{core,d,b}=await setup(t);const item=(await core.getHumanItems(b)).items[0];for(const config of [{visibility:'local'},{category:'style'},{selected:false}]){let current=await core.getDraft(b);let view=await core.saveHumanItems({...b,saveToken:current.saveToken,items:[{...review(item),...config}]});const v=await core.confirm({...b,saveToken:view.saveToken,author});assert.deepEqual((await core.exportVersion({...b,versionId:v.versionId})).humanItems,[]);current=await core.startRevision({...b,versionId:v.versionId});current=await core.saveDraft({...b,saveToken:current.saveToken,markdown:current.markdown+'\n\nDifferent '+JSON.stringify(config),source:'agent_inference'});}
let current=await core.getDraft(b);current=await core.saveDraft({...b,saveToken:current.saveToken,markdown:'# Report\n\nGenerated unchanged',source:'user_direct'});const empty=await core.getHumanItems(b);assert.equal(empty.items.length,0);assert.ok(empty.warnings.includes('DELETED_RETRACTIONS_UNSUPPORTED'));await assert.rejects(core.saveHumanItems({...b,saveToken:current.saveToken,items:[{...review(item),category:'retraction'}]}),{code:'INVALID_INPUT'});});
