import { fileURLToPath as testFilePath } from 'node:url';
process.chdir(testFilePath(new URL('../', import.meta.url)));
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createDemoApi, DEMO_STORAGE_KEY } from '../src/demo-api.mjs';
import { build } from 'esbuild';
import { chromium, expect } from '@playwright/test';
import { PDFDocument } from 'pdf-lib';
import { readFile, mkdir } from 'node:fs/promises';

test('offline demo: two flows, templates, edits, real PDF, history, mock publish and reopen', async () => {
  const result = await build({ stdin: { contents: `import React from 'react';import {createRoot} from 'react-dom/client';import {Workspace} from './src/client.jsx';function DemoHarness(){const [open,setOpen]=React.useState(false);return <><button onClick={()=>setOpen(true)}>周报工作台</button>{open && <Workspace close={()=>setOpen(false)}/>}</>};createRoot(document.getElementById('root')).render(<DemoHarness/>);`, loader:'jsx', resolveDir:process.cwd() }, bundle:true, write:false, format:'iife', jsx:'automatic', loader:{'.css':'text'} });
  const browser = await chromium.launch({ channel:process.env.BROWSER_CHANNEL || 'chrome', headless:true });
  const page = await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
  const outbound = [], errors = [];
  page.on('pageerror', e=>errors.push(e.message));
  await page.route('**/*', route => {
    if (/^(chrome|chrome-extension|blob):/.test(route.request().url())) return route.continue();
    if (route.request().isNavigationRequest() && route.request().url() === 'http://demo.test/') return route.fulfill({contentType:'text/html',body:'<!doctype html><html><meta charset="utf-8"><body><div id="root"></div></body></html>'});
    outbound.push(route.request().url()); return route.abort();
  });
  try {
    await mkdir('test-results',{recursive:true});
    await page.goto('http://demo.test/'); await page.addScriptTag({content:result.outputFiles[0].text});
    await page.getByRole('button',{name:'周报工作台',exact:true}).click();
    await page.getByRole('button',{name:'体验演示数据'}).click();
    await expect(page.getByRole('note')).toContainText('本地演示');
    await expect(page.getByLabel('生成与分析', {exact:true})).toBeVisible();
    await expect(page.getByLabel('报告正文')).toBeHidden();
    await page.getByLabel('模板名称',{exact:true}).fill('我的演示模板');
    await page.getByRole('button',{name:'保存为模板'}).click();
    await expect(page.getByLabel('选择模板')).toContainText('我的演示模板');
    await page.getByRole('combobox', {name:'选择模板'}).click();
    await expect(page.getByRole('listbox', {name:'分析模板'})).toBeVisible();
    await page.screenshot({path:'test-results/template-select.png'});
    await page.keyboard.press('Home');
    await page.keyboard.press('Enter');
    await expect(page.getByRole('combobox', {name:'选择模板'})).toContainText('默认模板');
    await page.getByRole('combobox', {name:'选择模板'}).press('ArrowDown');
    await page.keyboard.press('End');
    await page.keyboard.press('Enter');
    await expect(page.getByRole('combobox', {name:'选择模板'})).toContainText('我的演示模板');
    await page.getByRole('combobox', {name:'选择模板'}).click();
    await page.keyboard.press('Escape');
    await expect(page.getByRole('listbox', {name:'分析模板'})).toBeHidden();
    await expect(page.getByRole('dialog', {name:'周报审阅工作台'})).toBeVisible();
    await page.getByRole('button',{name:'删除模板'}).click();
    await expect(page.getByLabel('选择模板')).not.toContainText('我的演示模板');
    await page.getByLabel('商品',{exact:true}).fill('铜');
    await page.getByLabel('截止日期',{exact:true}).fill('2026-09-08');
    await page.getByLabel('分析要求（可选）',{exact:true}).fill('核对库存变化');
    await page.getByRole('button',{name:'生成演示周报',exact:true}).click();
    await expect(page.getByLabel('生成与分析',{exact:true})).toBeHidden();
    await expect(page.locator('.bn-editor')).toContainText('铜周报');
    await page.getByRole('button', { name: 'Markdown 实时浏览', exact: true }).click();
    await expect(page.locator('.cm-content')).toContainText('铜周报');
    const editorNode = await page.locator('.cm-editor').elementHandle();
    await page.getByRole('button',{name:'Markdown 实时浏览',exact:true}).click();
    const markdownPreview = page.getByLabel('Markdown 实时预览', {exact:true});
    await page.locator('.cm-content').fill('# 即时标题\n\n**粗体结论**\n\n| 指标 | 数值 |\n| --- | --- |\n| 库存 | 12 |\n\n<script>window.injected=true</script>\n\n[危险链接](javascript:alert(1))\n\n![外部图片](https://external.test/tracker.png)');
    await expect(markdownPreview.getByRole('heading', {name:'即时标题'})).toBeVisible();
    await expect(markdownPreview.locator('.rr-markdown-body strong')).toContainText('粗体结论');
    await expect(markdownPreview.getByRole('table')).toContainText('库存');
    assert.equal(await markdownPreview.locator('script, img, a[href^="javascript:"]').count(), 0);
    await expect(page.getByRole('button',{name:'导出 PDF',exact:true})).toBeDisabled();
    const left = await page.getByLabel('报告正文').boundingBox();
    const right = await markdownPreview.boundingBox();
    assert.ok(left.x + left.width <= right.x, 'Markdown reading preview sits beside source');
    await page.screenshot({path:'test-results/markdown-split.png'});
    await page.emulateMedia({colorScheme:'dark'});
    await page.screenshot({path:'test-results/markdown-split-dark.png'});
    await page.emulateMedia({colorScheme:'light'});
    await page.setViewportSize({width:390,height:900});
    assert.ok(await page.locator('.rr-main').evaluate(el=>el.scrollWidth<=el.clientWidth+1));
    await page.screenshot({path:'test-results/markdown-split-mobile.png'});
    await page.setViewportSize({width:1440,height:1000});
    assert.ok(await editorNode.evaluate(el=>el.isConnected), 'Switching previews preserves the editor');
    await page.locator('.cm-content').fill(Array.from({length:30}, (_,i) => `## 章节 ${i + 1}\n\n${'长文同步滚动检查。'.repeat(10)}\n\n| 项目 | 数据 |\n| --- | --- |\n| 库存 | ${i} |\n`).join('\n'));
    const sourceScroll = page.locator('.rr-canvas .cm-scroller');
    const readingScroll = page.locator('.rr-markdown-body');
    await expect(markdownPreview.getByRole('heading', {name:'章节 30',exact:true})).toHaveCount(1);
    await sourceScroll.evaluate(el => { el.scrollTop = el.scrollHeight; });
    await expect.poll(() => readingScroll.evaluate(el => el.scrollHeight - el.clientHeight - el.scrollTop)).toBeLessThan(3);
    await readingScroll.evaluate(el => { el.scrollTop = 0; });
    await expect.poll(() => sourceScroll.evaluate(el => el.scrollTop)).toBeLessThan(3);
    await readingScroll.evaluate(el => { const heading = [...el.querySelectorAll('h2')].find(n=>n.textContent==='章节 16'); el.scrollTop += heading.getBoundingClientRect().top - el.getBoundingClientRect().top; });
    await expect.poll(() => page.locator('.rr-canvas .cm-line').filter({hasText:/^## 章节 16$/}).evaluateAll(lines => {
      if (!lines.length) return 10000;
      return Math.abs(lines[0].getBoundingClientRect().top - lines[0].closest('.cm-scroller').getBoundingClientRect().top);
    })).toBeLessThan(40);
    await page.screenshot({path:'test-results/markdown-scroll-sync.png'});
    await page.locator('.cm-content').fill('# 铜演示周报\n\n这是我的人工修改，需核对来源。');
    await expect(page.getByRole('button',{name:'保存 / 重试'})).toBeDisabled();
    await expect(page.locator('.rr-status')).toContainText('PDF 已同步', {timeout:20000});
    const [exported] = await Promise.all([page.waitForEvent('download'), page.getByRole('button',{name:'导出 PDF',exact:true}).click()]);
    assert.ok((await PDFDocument.load(await readFile(await exported.path()))).getPageCount() >= 1);
    await expect(page.locator('.rr-sidebar')).toBeHidden();
    await page.getByRole('button',{name:'退出专注',exact:true}).click();
    await page.getByRole('button',{name:'重点人工信息',exact:true}).click();
    await page.getByLabel('重点条目').check();
    await page.getByRole('button',{name:'保存人工信息选择（仅本地）'}).click();
    await expect(page.locator('.rr-status')).toContainText('人工信息选择已本地保存');
    await page.getByRole('button',{name:/返回正文/}).click();
    await page.getByRole('button',{name:'PDF 实时浏览',exact:true}).click();
    await expect(page.locator('.cm-content')).toBeVisible();
    const pdfLeft = await page.getByLabel('报告正文').boundingBox();
    const pdfRight = await page.getByLabel('报告版式').boundingBox();
    assert.ok(pdfLeft.x + pdfLeft.width <= pdfRight.x, 'PDF sits beside editable source');
    await page.screenshot({path:'test-results/pdf-split.png'});
    const [download] = await Promise.all([page.waitForEvent('download'), page.getByRole('link',{name:/下载演示 PDF/}).click()]);
    const bytes = await readFile(await download.path());
    assert.equal(bytes.subarray(0,5).toString(),'%PDF-');
    assert.ok((await PDFDocument.load(bytes)).getPageCount() >= 1);
    await page.getByRole('button',{name:'可视化编辑',exact:true}).click();
    await page.getByRole('button', {name:'退出专注', exact:true}).click();
    await page.getByRole('button',{name:'模拟确认发布',exact:true}).click();
    await page.getByRole('button',{name:'确认模拟发布',exact:true}).click();
    await expect(page.locator('.rr-status')).toContainText('模拟发布完成');
    await expect(page.locator('.bn-editor')).toHaveAttribute('contenteditable','false');
    await page.getByRole('button',{name:'版本历史与差异',exact:true}).click();
    await expect(page.locator('.rr-review-view-body')).toContainText('v1');
    await page.getByRole('button',{name:'开启新一轮修订'}).click();
    await expect(page.locator('.bn-editor')).toHaveAttribute('contenteditable','true');
    await page.getByRole('button',{name:'1 生成与分析',exact:true}).click();
    await expect(page.locator('.rr-generation-stage')).toBeVisible();
    await page.getByRole('button',{name:'2 可视化编辑',exact:true}).click();
    await expect(page.locator('.bn-editor')).toContainText('这是我的人工修改');
    await mkdir('test-results',{recursive:true});
    await page.screenshot({path:'test-results/demo-editor.png'});
    await page.getByRole('button',{name:'1 生成与分析',exact:true}).click();
    await page.screenshot({path:'test-results/demo-generation.png'});
    await page.setViewportSize({width:390,height:900});
    assert.ok(await page.locator('.rr-workspace').evaluate(el=>el.scrollWidth<=el.clientWidth+1));
    await page.getByRole('button',{name:'关闭',exact:true}).click();
    await page.reload(); await page.addScriptTag({content:result.outputFiles[0].text});
    await page.getByRole('button',{name:'周报工作台',exact:true}).click();
    await page.getByRole('button',{name:'体验演示数据'}).click();
    await page.getByRole('button',{name:/铜周报.*演示/}).click();
    await expect(page.locator('.bn-editor')).toContainText('这是我的人工修改');
    assert.deepEqual(outbound,[], 'Demo must never access Host, database, models, fonts or publication services');
    assert.deepEqual(errors,[]);
  } finally { await browser.close(); }
});
