import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {ReportStore} from '../../report-core/src/index.mjs';
import {createReviewHost,validateHumanItems,registerReviewTools} from '../src/index.mjs';
async function fixture(t){const root=await mkdtemp(join(tmpdir(),'review-items-'));t.after(()=>rm(root,{recursive:true,force:true}));const core=new ReportStore({rootDir:root});const api=createReviewHost({core,pdf:{},sessions:{get:id=>id==='s'?{id}:undefined},getConnector:()=>({identity:async()=>({verified:true,credentialPurpose:'publish',principal:{userId:'u',username:'fixture'}}),createReviewHost(){throw Error('must not write');}})},{allowedSessionIds:['s'],publishKbId:'kb'});t.after(()=>api.dispose());let draft=await core.createDraft({sessionId:'s',title:'test',markdown:'# Title\n\nGenerated'});draft=await core.saveDraft({sessionId:'s',reportId:draft.reportId,saveToken:draft.saveToken,markdown:'# Title\n\nHuman correction',source:'user_direct'});return {core,api,draft,b:{sessionId:'s',reportId:draft.reportId}};}
test('human items exact allowlist rejects unknown fields and duplicate refs',()=>{assert.throws(()=>validateHumanItems([{annotationId:'a',category:'style',selected:false,visibility:'local',content:'forged'}]),{code:'INVALID_INPUT'});assert.throws(()=>validateHumanItems([{annotationId:'a',category:'oops',selected:false,visibility:'local'}]),{code:'INVALID_INPUT'});});
test('human-only settings obey session, token, privacy and frozen draft',async t=>{const {core,api,draft,b}=await fixture(t);const v=await api.dispatchHuman({...b,action:'humanItems',saveToken:draft.saveToken});assert.equal(v.items.length,1);assert.equal(v.items[0].selected,false);assert.equal(v.items[0].visibility,'local');const items=[{annotationId:v.items[0].annotationId,category:'correction',selected:true,visibility:'public',publicSource:'field note',localNote:'PRIVATE_NOTE'}];const saved=await api.dispatchHuman({...b,action:'saveHumanItems',saveToken:v.saveToken,items});assert.notEqual(saved.saveToken,v.saveToken);assert.ok(!JSON.stringify(saved).includes('PRIVATE_NOTE'));await assert.rejects(api.dispatchHuman({...b,action:'saveHumanItems',saveToken:v.saveToken,items}),{code:'CONFLICT'});await assert.rejects(api.dispatchHuman({...b,sessionId:'other',action:'humanItems'}),{code:'SESSION_FORBIDDEN'});await assert.rejects(api.dispatchHuman({...b,action:'humanItems',evil:'x'}),{code:'INVALID_INPUT'});await core.confirm({...b,saveToken:saved.saveToken,author:{authorId:'u',displayName:'fixture'}});const frozen=await api.dispatchHuman({...b,action:'humanItems'});assert.equal(frozen.status,'confirmed');await assert.rejects(api.dispatchHuman({...b,action:'saveHumanItems',saveToken:frozen.saveToken,items}),{code:'REVISION_REQUIRED'});// Selected public human item becomes an independent publish plan entry (no silent block). The fixture connector must not write; only the plan is prepared here.
const plan=await api.dispatchHuman({...b,action:'publishPlan',versionId:'V1'});assert.ok(plan.items.some(i=>i.type==='human'));assert.ok(!JSON.stringify(plan).includes('PRIVATE_NOTE'));});
test('no human item settings methods or tools are exposed to Agent',async t=>{const {api}=await fixture(t),names=[];registerReviewTools({get:n=>n==='tools'?{register:d=>{names.push(d.name);return()=>{};}}:api},api);assert.deepEqual(names,['run19_report_list','run19_report_read','run19_report_save']);assert.equal(api.saveHumanItems,undefined);assert.equal(api.humanItems,undefined);});
