import test from 'node:test';
import assert from 'node:assert/strict';
import {preparePublicationManifest as prepare,resolvePublicationMarkdown as resolve,deriveVariety} from '../src/publication-manifest.mjs';
const hash='a'.repeat(64),uri='resource://abcdefghijklmnopqrstuv';
function fixture(){return {reportId:'r_123',versionId:'V1',title:'锡 SN：润洲周度报告（2026-09-09）',markdown:'# 锡\n\n人工纠错内容\n\n![库存](asset:img1)\n\n![库存](asset:img1)',assets:[{id:'img1',sha256:hash,path:'/Users/private/chart.png'}],annotations:[{id:'a1',target:{startLine:3,endLine:3,quote:'人工纠错内容'},public:true,source:'user_direct',authorId:'u1',displayName:'测试用户',completedAt:'2026-09-08T14:05:00.000Z'}],humanItems:[{id:'human_a1',annotationId:'a1',category:'correction',source:'user_direct',content:'人工纠错内容',authorId:'u1',displayName:'测试用户',completedAt:'2026-09-08T14:05:00.000Z',publicSource:'现场记录'}]};}
const binding={assetId:'img1',sha256:hash,kbId:'kb1',resourceUri:uri,knowledgeId:'knowledge1'};
test('deriveVariety stops at report-type word / non-CJK separator / end, so 锡周报→锡 and 碳酸锂周报→碳酸锂',()=>{
  assert.equal(deriveVariety('锡周报'),'锡');
  assert.equal(deriveVariety('锡 SN：润洲周度报告（2026-09-09）'),'锡');
  assert.equal(deriveVariety('碳酸锂周报'),'碳酸锂');
  assert.equal(deriveVariety('氧化铝周报'),'氧化铝');
  assert.equal(deriveVariety('锡'),'锡');
  assert.equal(deriveVariety(''),'');
});
test('owned immutable ordered manifest excludes private fields and deduplicates same asset references',()=>{const v=fixture();v.localNote='SECRET';v.humanItems[0].localNote='SECRET';v.humanItems[0].prompt='SECRET';const p=prepare(v,{kbId:'kb1'});assert.deepEqual(p.items.map(i=>i.type),['image','report','pdf','human']);assert.equal(p.items[0].title,'锡-周报-2026-09-09-库存');assert.ok(Object.isFrozen(p.items[3].human));assert.ok(!JSON.stringify(p).includes('SECRET'));assert.ok(!JSON.stringify(p).includes('/Users'));assert.equal(p.items[3].human.annotationId,'a1');assert.match(p.items[1].markdown,/2026-09-08-14-05 用户测试用户/);assert.match(p.items[1].markdown,/显示尚待验证/);v.markdown='changed';assert.match(p.items[1].markdown,/人工纠错内容/);});
test('ordinary source URL text stays inert while images remain restricted',()=>{const v=fixture();v.markdown+='\n\n数据来源：http://127.0.0.1:5100';assert.match(prepare(v,{kbId:'kb1'}).items.find(i=>i.type==='report').markdown,/http:\/\/127.0.0.1:5100/);});
test('public source cannot inject images and generated metadata is Markdown escaped',()=>{const v=fixture();v.humanItems[0].publicSource='![tracker](https://evil/image)';assert.throws(()=>prepare(v,{kbId:'kb1'}),{code:'INVALID_PUBLIC_SOURCE'});v.humanItems[0].publicSource='[source](https://example.org)';v.title='![title](https://evil)';v.annotations[0].displayName='![name](https://evil)';v.humanItems[0].displayName=v.annotations[0].displayName;const p=prepare(v,{kbId:'kb1'}),h=p.items.find(i=>i.type==='human');assert.ok(h.markdown.includes(String.raw`\!\[title\]`));assert.ok(h.markdown.includes(String.raw`\!\[name\]`));assert.ok(h.markdown.includes(String.raw`\[source\]`));});
test('digest stable across path/private changes and changes for content hashes or human metadata',()=>{const a=fixture(),b=fixture();b.assets[0].path='/elsewhere';b.humanItems[0].localNote='secret';assert.equal(prepare(a,{kbId:'kb1'}).digest,prepare(b,{kbId:'kb1'}).digest);b.assets[0].sha256='b'.repeat(64);assert.notEqual(prepare(a,{kbId:'kb1'}).digest,prepare(b,{kbId:'kb1'}).digest);b.assets[0].sha256=hash;b.humanItems[0].publicSource='修订来源';assert.notEqual(prepare(a,{kbId:'kb1'}).digest,prepare(b,{kbId:'kb1'}).digest);});
test('unknown missing duplicate ambiguous and unsupported image references fail explicitly',()=>{for(const mutate of [v=>v.assets=[],v=>v.assets.push({...v.assets[0]}),v=>v.markdown+='\n![不同图注](asset:img1)',v=>v.markdown+='\n![x](https://evil)',v=>v.markdown+='\n<img src="evil">',v=>v.markdown+='\n![x](data:image/png;base64,A)',v=>v.markdown+='\n![x][ref]',v=>v.assets.push({id:'unused',sha256:hash})]){const v=fixture();mutate(v);assert.throws(()=>prepare(v,{kbId:'kb1'}));}});
test('human association requires current version content and public inputs',()=>{for(const mutate of [v=>v.humanItems[0].content='deleted text',v=>v.humanItems[0].visibility='local',v=>v.humanItems[0].category='style',v=>v.humanItems[0].source='agent_inference',v=>v.humanItems[0].completedAt='tomorrow']){const v=fixture();mutate(v);assert.throws(()=>prepare(v,{kbId:'kb1'}));}});
test('resource binding strict scope hash and canonical grammar; resolution never mutates local plan',()=>{const v=fixture(),p=prepare(v,{kbId:'kb1'});const result=resolve(p,[binding]);assert.equal(result.split(uri).length-1,2);assert.ok(p.items[1].markdown.includes('asset:img1'));assert.ok(v.markdown.includes('asset:img1'));for(const b of [{...binding,kbId:'other'},{...binding,sha256:'b'.repeat(64)},{...binding,resourceUri:uri+'?token=x'},{...binding,resourceUri:'resource://short'},{...binding,resourceUri:'https://x'},{...binding,assetId:'unknown'}])assert.throws(()=>resolve(p,[b]));assert.throws(()=>resolve(p,[]));assert.throws(()=>resolve(p,[binding,binding]));assert.throws(()=>resolve(JSON.parse(JSON.stringify(p)),[binding]));});
